Feat: controller
brahmkshatriya/echo pull request #45
Opened 2024-11-23 09:03 UTC by rebelonion

# Fixes: 
 - Calling ``onExtensionSelected`` on disabled extensions other than music 
 - ``SettingTextInput`` not updating the shown value immediately after setting

# Additions
## MessagePostClient
- Allows an extension to hook into ``mutableMessageFlow`` to post messages other than errors
- Interface uses delegate/callback

## CloseableClient
- Allows extensions to close resources the app closes
- Tied to the player service which should be the last thing running in the app
- In my case this was useful for closing a websocket that otherwise kept running after the app was closed

## ControllerClient
- Allows an extension to perform actions directly onto the player
- Uses functions for app->extension communication and callbacks for extension->app communication
- Nicely documented

## examples:
### [Echo Song Skipper](https://github.com/rebelonion/echo-song-skipper)
- skips songs based off of song or artist name automatically

### [Echo Remote Control](https://github.com/rebelonion/echo-remote-control)
- connects to a control app through a websocket server to remotely control playback

2024-11-25 16:41 UTC, brahmkshatriya requested changes
I am thinking, it would be better to just combine tracker extensions and controller extensions to a simply `PlayerExtension` (suggest better name if you can think any)
because to me, it seems excessive to have so many types of different extensions.

2024-11-25 16:41 UTC, brahmkshatriya commented on common/src/main/java/dev/brahmkshatriya/echo/common/clients/MessagePostClient.kt
It would be better if you use this class here. (you can move this class to common package)
https://github.com/brahmkshatriya/echo/blob/946c84da48869f1dd0fa94e691ef4e4271642edb/app/src/main/java/dev/brahmkshatriya/echo/viewmodels/SnackBar.kt#L32-L35

2024-11-25 16:41 UTC, brahmkshatriya commented on common/src/main/java/dev/brahmkshatriya/echo/common/clients/CloseableClient.kt
Rename to `onClose()`

2024-11-25 16:41 UTC, brahmkshatriya commented on common/src/main/java/dev/brahmkshatriya/echo/common/clients/ControllerClient.kt
I recommend using `MutableSharedFlow<T>` instead of `suspend (t: T) -> Unit` for all the `var on...Request`, and converting this abstract class to an interface.

you can see how `MutableSharedFlow` works here: https://developer.android.com/kotlin/flow/stateflow-and-sharedflow#sharedflow

Also, it'd be better if you move all data classes and enums to `models` package

2024-11-25 16:42 UTC, brahmkshatriya commented
Thanks again for the PR!

2024-11-25 16:43 UTC, brahmkshatriya commented on common/src/main/java/dev/brahmkshatriya/echo/common/clients/MessagePostClient.kt
and also using `MutableSharedFlow<Message>` instead of those functions.

2025-02-17 14:19 UTC, itsmechinmoy commented
ok but what happened to this?

2025-03-10 07:16 UTC, rebelonion commented
gonna close this and submit again when I have time to update

2025-03-10 07:16 UTC, closed without merging